name: Scheduled Scrape and Deploy

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Scrape
        run: npm run scrape

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}

          git add data/richmond/avg.csv
          git add data/richmond/vendors.csv
          git add public/data/richmond/avg.csv
          git add public/data/richmond/vendors.csv
          # Only commit if there are actually changes to avoid errors
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated data update" && git push)


      - name: build 
        run: npm run build

      - name: Deploy
        run: npm run deploy
        env:
          DEPLOY_TOKEN: ${{ secrets.GH_TOKEN }}